In [1]:
import numpy as np

In [2]:
# create array of values from 0 to 10
arr = np.arange(0, 11)

In [3]:
# view array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# add each value in the array to itself (double each value)
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [5]:
# add 100 to each value in the array
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [6]:
# calculate square root for each value in the array
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [7]:
# calculate exponential for each value in the array
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [8]:
# view array - note that the above operations did not occur in-place
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])