In [1]:
import numpy as np

In [2]:
# create array of integers from 0 to 10
arr = np.arange(0, 11)

In [3]:
# view array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# retrieve value at index 8 from array
arr[8]

8

In [5]:
# slice array; retrieve values at indices 1-4 (lower index included, upper index excluded)
arr[1:5]

array([1, 2, 3, 4])

In [6]:
# retrieve all values with indices < 6
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
# retrieve all values with indices < 6 again; note that arr[0:6] == arr[:6]
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
# retrieve all values with indices >= 5
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
# slice and set multiple array values at once
arr[0:5] = 100

In [10]:
# view array
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
# create new array
arr = np.arange(0, 11)

In [12]:
# view array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
# NOTE: CREATING A SLICE CALLS BY REFERENCE - CHANGING SLICE WILL CHANGE ORIGINAL
slice_of_arr = arr[0:6]

In [14]:
# check slice of array
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
# reassign all values in array slice to 99
slice_of_arr[:] = 99

In [16]:
# check slice after reassigning values
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
# note that original array values changed after changing the slice
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
# create copy of array if you do not want to change original array
arr_copy = arr.copy()

In [19]:
# view array
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
# view array copy (same as original array)
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
# set all values in array copy to 100
arr_copy[:] = 100

In [22]:
# view array copy
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
# check original array - note that original array was not affected by changing its copy
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
# create 2D array with shape (3, 3)
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [25]:
# view array
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
# retrieve the value at index 0 from the subarray at index 0
arr_2d[0][0]

5

In [27]:
# retrieve entire subarray at index 0
arr_2d[0]

array([ 5, 10, 15])

In [28]:
# retrieve the value at index 1 from the subarray at index 1
arr_2d[1][1]

25

In [29]:
# retrieve the value at index 1 from the subarray at index 2
arr_2d[2][1]

40

In [30]:
# same as above, but different notation (which is best practice?)
arr_2d[2, 1]

40

In [31]:
# retrieve the value at index 2 from the subarray at index 1
arr_2d[1, 2]

30

In [32]:
# retrieve the values with indices >= 1 from the subarrays with indices < 2
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [33]:
# retrieve all values with indices >= 0 from the subarrays with indices >= 1
arr_2d[1:, 0:]

array([[20, 25, 30],
       [35, 40, 45]])

In [34]:
# retrieve all values with indices >= 1 from the subarrays with indices >= 1
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [35]:
# create new array
arr = np.arange(1, 11)

In [36]:
# view array
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# use comparison operator on array to create boolean array
bool_arr = arr > 5

In [38]:
# view boolean array
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [39]:
# pass boolean array into original array for conditional selection
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [40]:
# same thing as above (conditional selection) but in one step
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [41]:
# retrieve all values in array less than 3
arr[arr < 3]

array([1, 2])

In [42]:
# create array with values 0-49 and shape (5, 10)
arr_2d = np.arange(50).reshape(5, 10)

In [43]:
# view array
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
# retrieve the values at indices 3 and 4 from the subarrays at indices 1 and 2
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

In [45]:
# retrieve all values with indices >= 7 from the subarrays with indices >= 3
arr_2d[3:, 7:]

array([[37, 38, 39],
       [47, 48, 49]])

In [46]:
# create array of zeros with shape (10, 10)
arr2d = np.zeros((10, 10))

In [47]:
# view array
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [48]:
# find length of multidimensional array by checking shape of a one-dimensional subarray
arr_length = arr2d.shape[0]

In [49]:
# check array length
arr_length

10

In [50]:
# set each value to its subarray's index
for i in range(arr_length):
    arr2d[i] = i
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [51]:
# use fancy indexing to select rows and columns out of order
arr2d[[2, 7, 5, 3]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])