In [1]:
import numpy as np

In [2]:
# create list
my_list = [1, 2, 3]

In [3]:
# create NumPy array using values from list
arr = np.array(my_list)

In [4]:
# view array
arr

array([1, 2, 3])

In [5]:
# create matrix (basically list of lists?)
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
# view matrix
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
# use matrix to create 2D NumPy array
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# create array (min, max, interval)
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
# create array of 3 zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
# create 2D array of zeros with shape (2, 3)
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
# create array of 4 ones
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
# create array of ones with shape (3, 4)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# np.linspace(min, max, # of values) - create array of evenly spaced values between two numbers
np.linspace(0, 5, 50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [14]:
# create array with ones on diagonal and shape (4, 4)
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# create array of uniform random values between 0 and 1
np.random.rand(5)

array([0.02293358, 0.2580676 , 0.45623924, 0.88250975, 0.60777253])

In [16]:
# create array of uniform random values between 0 and 1 with shape (5, 5)
np.random.rand(5, 5) 

array([[0.06393511, 0.53326439, 0.48445975, 0.04771729, 0.12855701],
       [0.67366067, 0.57830055, 0.99932088, 0.12624037, 0.13896019],
       [0.98751875, 0.87557487, 0.16633047, 0.20390813, 0.55108308],
       [0.86045202, 0.01605523, 0.11940768, 0.79497171, 0.38108893],
       [0.67139985, 0.1917672 , 0.5368589 , 0.92144755, 0.85424514]])

In [17]:
# create array of five random numbers from standard normal distribution - NOT uniform
np.random.randn(5)

array([ 0.14878854, -0.65088869,  0.07453101, -1.92860422, -0.29973634])

In [18]:
# create array of random numbers from standard normal distribution with shape (4, 4)
np.random.randn(4, 4)

array([[ 1.37491987, -0.72252925, -1.10708714,  0.41238117],
       [ 1.54477492, -2.70097984, -0.26020153, -1.13678613],
       [ 1.25417431, -1.402558  , -1.14465653,  0.16627561],
       [ 0.40601972,  0.48054826,  0.15313498, -0.45894852]])

In [19]:
# np.random.randint(min, max, # of values) - create array of random integers
np.random.randint(1, 100, 10)

array([51, 77, 27, 50, 10, 82, 24, 36, 12, 47])

In [20]:
# create array with values 0-24 (25 is excluded)
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [21]:
# reshape array into 2D array with shape (5, 5)
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
# note that reshape() is not inplace
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
# create new array with specified shape
arr = arr.reshape(5, 5)

In [24]:
# array will now retain its new shape
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
# verify shape of array
arr.shape

(5, 5)

In [26]:
# check array type
arr.dtype

dtype('int64')

In [27]:
# create array with ten random values between 0 and 50
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([14,  6, 34, 36, 40, 18, 28, 23,  6, 29])

In [29]:
# return maximum value in array
ranarr.max()

40

In [30]:
# return minimum value in array
ranarr.min()

6

In [31]:
# return index of maximum value in array
ranarr.argmax()

4

In [32]:
# return index of minimum value in array
ranarr.argmin()

1

In [33]:
# generate random integer
np.random.randint(2, 10)

7